# Generated by Django 4.1.2 on 2022-10-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contenido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=100, null=True)),
                ("urlimagen", models.CharField(blank=True, max_length=200, null=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("detalle", models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                "db_table": "contenido",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "tipo",
                "managed": False,
            },
        ),
    ]
